betagouv/e-controle

ecc/urls.py, magicauth/templates/magicauth/email.html, magicauth/templates/magicauth/email.txt, templates/base.html
=> Correction ortho

.babelrc, .gitignore, Dockerfile, README.md, docker-entrypoint.sh, package-lock.json, package.json, static/src/index.js, static/src/users/User.vue, templates/base.html, templates/base_tabler.html, templates/ecc/questionnaire_list.html
Add a demo app to include a vuejs component in django template
Add nodejs and npm command to docker
=> Add parcel and vuejs boilerplate

control/api_views.py, control/serializers.py, control/tests/test_api.py, ecc/urls.py
Il manque (je ferai une 2e PR): 
- logger les actions
- gerer les erreurs (si le save d'un theme ou d'une question fail par exemple)
=> Questionnaire api

control/api_views.py, control/tests/test_api.py, ecc/apps.py
- action logging
- better errors.
=> Questionnaire-api : extra logging and validation 

control/views.py, ecc/urls.py, static/src/questionnaires/QuestionnaireBodyCreate.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireDetail.vue, static/src/questionnaires/QuestionnaireMetadataCreate.vue, static/src/questionnaires/QuestionnairePreview.vue, templates/ecc/questionnaire_create.html, templates/ecc/questionnaire_list.html
First version : 
- save at the end of the creation pages (if you reload or navigate away you lose your work!)
- basic front end validation using html
- only urls with control allowed for the user will display
=> Questionnaire-create : full stack

package-lock.json, package.json, requirements.txt
Pour npm, j'ai utilisé https://www.npmjs.com/package/npm-upgrade
Pour pip, j'ai utilisé : "pur" et j'ai manuellement mis à jour django
=> Upgrade des packages pip et npm

static/css/custom.css, static/src/details/Question.vue, static/src/questionnaires/QuestionnaireDetail.vue, static/src/questionnaires/QuestionnaireMetadataCreate.vue
fixing issue #149
Small display fix to display whitespace.
=> New lines in questions

control/api_views.py, control/tests/test_api.py, static/src/questionnaires/QuestionnaireBodyCreate.vue
- Add theme deletion to questionnaire update/create API
- Theme deletion is already present in UI, but fix bug where it was always the first theme being deleted.
=> Delete themes in draft questionnaire

static/src/questionnaire-list.js, static/src/utils/HelpTooltip.vue, templates/ecc/questionnaire_list.html
=> Help tooltips

control/docx.py, ecc/settings.py
We are now getting the path from settings
=> Bug sur le dossier du template Docx

static/css/custom.css, static/src/questionnaires/QuestionnaireBodyCreate.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireMetadataCreate.vue, static/src/questionnaires/QuestionnairePreview.vue, static/src/utils/WizardStep.vue
- add a wizard bar to make it clear which step we're on
- add titles to each step, and place them in a card
- add a cancel button to escape the wizard
=> Wizard format for the QuestionnaireCreate pages

control/views.py, static/css/custom.css, static/src/questionnaires/QuestionnaireDetailForPreview.vue, static/src/questionnaires/QuestionnaireDetailPage.vue, static/src/questionnaires/QuestionnaireMetadata.vue, static/src/questions/ResponseFileList.vue, static/src/themes/ThemeListSidebar.vue
=> Corbeille : openlab changes

static/css/custom.css, static/src/questions/QuestionBox.vue, static/src/questions/QuestionFileList.vue, static/src/questions/ResponseDropzone.vue, static/src/questions/ResponseFileList.vue
=> Fix display bug where empty question bodies will open when clicked

static/src/utils/ConfirmModal.vue
- Buttons are now optional
- Add event to close button
=> Petits changement sur la modal de confirmation

static/src/controls/ControlCreate.vue, static/src/questionnaires/QuestionnaireBodyCreate.vue, static/src/questionnaires/QuestionnaireMetadataCreate.vue
Added frontend error validation for : 
- theme title < 255 char (in QuestionnaireBodyCreate.vue)
- questionnaire title < 255 char (in QuestionnaireMetadataCreate.vue)
- control title and depositing organization < 255 char (in ControlCreate.vue)
=> Bugfix : add frontend validation for theme name above 255 char

static/src/controls/ControlCreate.vue
Diffed against branch "bugfix/theme-name-less-than-255-char" instead of develop, to avoid conflicts.
=> Fix bug blocking display of error messages (#250)

control/api_views.py, control/models.py, control/tests/test_api_response_file.py, control/upload_path.py, control/views.py, static/src/questions/ResponseFileList.vue, templates/ecc/trash.html
Diffé contre feature/corbeille-webdav, en attendant sa review.
=> Corbeille : finitions

static/src/questionnaires/QuestionnaireCreate.vue
For issue : https://github.com/betagouv/e-controle/issues/237
Success message was showing in error case.
=> Bugfix : show questionnaire create success message on success only

control/admin.py, control/models.py, control/permissions.py, control/serializers.py, control/tests/test_api_questionnaire.py, control/tests/test_pages.py, control/views.py, docs/releases/1.3.1.md, docs/releases/1.3.md, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireDetailForPreview.vue, static/src/questionnaires/QuestionnaireDetailPage.vue, static/src/questionnaires/QuestionnairePreview.vue, templates/base.html, templates/ecc/questionnaire_list.html
=> Hotfix : single author for drafts

control/models.py, control/serializers.py, static/css/custom.css, static/src/questionnaires/PublishConfirmModal.vue, static/src/questionnaires/QuestionnaireBodyCreate.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireDetailPage.vue, static/src/questionnaires/QuestionnaireMetadataCreate.vue, static/src/questionnaires/QuestionnairePreview.vue, static/src/utils/ConfirmModal.vue, static/src/utils/EmptyModal.vue, static/src/utils/Wizard.vue, static/src/utils/WizardStep.vue, templates/ecc/questionnaire_detail.html, templates/ecc/questionnaire_list.html
Page Accueil: 
- ajouter un Tag "brouillon"
- enlever la couleur de fond pour les brouillons
Page Creation/modification de brouillon :
- tag "Brouillon" dans le titre
- Wizard : 
- checks verts pour les etapes accomplies
- naviguer en clickant sur les numeros d’etapes
- ajout d'une sauvegarde quand on clicke sur précédent
- icones sur les boutons
- espacer le bouton Publier
- Modals de publication
- Ajouter des checkboxes pour faire confirmer la publication
- Ajout d'un modal "en cours..."
- Ajout d'un modal "c'est fini"
- retour a l'accueil sans redonner acces a la page 
Avec du refactoring, pour QuestionnaireCreate.vue en particulier (more to come in next PR, with tests)
=> Publish questionnaire : UI changes

package-lock.json, package.json, static/src/questionnaires/PublishConfirmModal.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnairePreview.vue, static/src/questionnaires/test/QuestionnairePreview.spec.js, static/src/utils/testUtils.js, tests/jest_setup.js
If there is an error when publishing the questionnaire, go back to the Publish modal, with an error message.
=> Publish questionnaire : display error

user_profiles/api_views.py, user_profiles/serializers.py
Now we log if it's a inspector or an autdited user
=> Logs sur la gestion utilisateurs: distinction contrôleur/contrôlé

templates/user_profiles/email_add_user.html, templates/user_profiles/email_add_user.txt, templates/user_profiles/email_remove_user.html, templates/user_profiles/email_remove_user.txt
Suppression de la personnalisation de l'email.
=> Modif texte email add user

control/models.py, control/serializers.py, control/views.py, static/css/custom.css, static/src/controls/ControlCreate.vue, static/src/controls/ControlListSidebar.vue, static/src/controls/ControlTitle.vue, static/src/controls/WebdavTip.vue, static/src/questionnaire-list.js, static/src/themes/ThemeListSidebar.vue, static/src/users/AddUserModal.vue, static/src/users/UserSection.vue, static/src/utils/CollapsibleSidebarItem.vue, static/src/utils/ConfirmModalWithWait.vue, static/src/utils/Sidebar.vue, static/src/utils/SidebarItem.vue, templates/base.html, templates/ecc/questionnaire_list.html
First wave.
Only questionnaire-list is done for now. 
- sidebar with control list
- Add Control button moved to top, and form moved into a modal instead of dropdown
- layout changes because the screen is narrower with the sidebar : 
- title of control displayed on several lines
- People in the control : displayed in column instead of row
Coming in next PR, also for questionnaire-detail page : 
- Select a control on page load (right now no control is displayed, it's confusing)
- lots of console errors from Vue, there is a problem with how the v-show is loaded (still investigating that)
=> Navigation improvements

reporting/tasks.py, reporting/tests/test_email.py, utils/email.py
Because the utility send function was changed.
=> Problème avec les envois d'email

docs/releases/1.8.md, static/src/controls/ControlPage.vue, static/src/controls/ControlTitle.vue, static/src/utils/Sidebar.vue, templates/login/login.html, tos/templates/tos/welcome.html
- Page Approuver les CGU (quand on est redirigé dessus) : le menu est absent --> l'affichage est bizarre
-> realigné le nom de l'utilisateur en haut
- pas de Logo « Cour des comptes » sur la page de connexion 
-> done
- Creer le premier espace d'un utilisateur : menu ok –-> Pas de bouton pour créer un espace de dépôt 
-> ajouté le bouton, pour les utilisateurs contrôleurs
- Titres longs dans le menu --> Modification pas sauvegardé si j’appuie seulement sur « modifier » puis dans un autre espace. Il faut nécessairement recharger la page pour que le nouveau titre apparaisse
-> ajouté un rechargement de page
=> Sidebar menu 2 : fix some bugs

tos/templates/tos/welcome.html
Suppression d'une partie de phrase obsolète
=> Suppression phrase

static/src/utils/Sidebar.vue
=> Sidebar menu 3 : Change menu titles

static/src/questions/ResponseDropzone.vue, templates/ecc/questionnaire_detail.html
Extend the timeout to 5min (which we think corresponds to apache timeout, to be tested) for dropzone uploads.
Style the thumbnails for better visibility of file status.
=> Dropzone timeout

static/css/custom.css, static/src/controls/ControlTitle.vue, static/src/controls/WebdavTip.vue, static/src/questionnaires/QuestionnaireMetadata.vue, static/src/users/UserList.vue, static/src/utils/BootstrapSize.vue, static/src/utils/Sidebar.vue, templates/ecc/faq.html, templates/ecc/trash.html, templates/login/email_sent.html
- la page "Email envoyé" doit etre centree
- les boutons "Aller a la corbeille" etc doivent etre dans la boite
- les titres d'espace et nom de dossier webdav tres longs doivent etre affichés sans dépasser des boites (dans la page de l'espace)
- le popup "C'est copié" est visible
Les pages sont tjs un petit peu trop larges pour l'ecran. Tant pis.
=> Layout fixes for IE

static/src/controls/WebdavTip.vue, static/src/questionnaire-create.js, static/src/questionnaire-detail.js, static/src/questionnaires/QuestionnaireDetailPage.vue, static/src/session-management.js, static/src/sidebar.js, static/src/utils/Sidebar.vue, static/src/utils/polyfills.js, templates/base.html, templates/footer.html
- fix the copying of webdav link for IE
- polyfill Element.remove() for IE
- fix some invalid HTML
=> Fixes for IE bugs for 1.9

static/css/custom.css, templates/login/login.html
Footer was displayed wrong : 
-  in the middle of the page in the login page (all browsers)
- on the side on Vue pages (IE only)
=> Footer : fix display for all browsers

static/src/controls/ControlTitle.vue
When modifying Control, display the value of the reference_code, but non-editable.
Switch order of fields.
=> Display reference code when modifying control

.eslintrc.json, package-lock.json, package.json, static/css/custom.css, static/src/questionnaires/QuestionnaireBodyCreate.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnairePreview.vue, static/src/utils/Wizard.vue, static/src/utils/WizardStep.vue, static/src/utils/backend.js, templates/ecc/questionnaire_create.html
Allow navigation to previously done steps.
For us, with 3 steps, this means adding jumping from step 3 to step 1.
Also, cleanup :
+ extra plugins and settings for eslint for linting vue files 
+ linted files in PR
+ moved css into vue components to make it scoped
=> Wizard : allow navigation backwards

static/src/controls/ControlCreate.vue, static/src/controls/ControlTitle.vue, static/src/users/AddUserModal.vue, static/src/users/RemoveUserModal.vue, static/src/users/UpdateUserModal.vue, static/src/users/UserList.vue, static/src/utils/Sidebar.vue, static/src/utils/backend.js, templates/base.html, templates/ecc/trash.html, templates/user_profiles/email_add_user.html, templates/user_profiles/email_add_user.txt, templates/user_profiles/email_remove_user.html, templates/user_profiles/email_remove_user.txt
J'ai remplacé "organisme" par "Administration/Entreprise"
Edit : finalement on enlève le champ "organisme" des formulaires pour creer/modifier les utilisateurs, puisqu'il n'est pas utilisé dans l'interface.
En bonus, correction de vocabulaire dans l'interface (contrôle vs procédure vs espace de dépôt) et linting du code JS.
=> Update/remove name "Organisme" for User

static/src/questionnaires/QuestionnaireCreate.vue
Solves https://github.com/betagouv/e-controle/issues/401
=> Bugfix : questionnaire create displays empty questionnaire

control/models.py, static/src/questionnaires/QuestionnaireCreate.vue, templates/ecc/questionnaire_create.html
Fix for #400 
Do not display the SwapEditorButton when there is no other inspector to transfer to.
=> Bugfix : single controller doesnt transfer rights

templates/login/email_sent.html
J'ai modifié le texte pour essayer de diminuer la gestion des "mailinblack"
=> Update message email send

control/serializers.py, control/tests/test_api.py
=> Move themes : backend

templates/login/login.html
The login form was too low on the page, users with small laptops didn't always see it because they didn't scroll down.
Move the login form higher up on the page.
=> Move up login form

static/src/questionnaires/QuestionnaireList.vue, static/src/questionnaires/QuestionnaireMetadata.vue, static/src/utils/backend.js
Implement the "Export" button in the dropdown menu for questionnaires, on the control page.
=> Export button in dropdown menu

control/admin.py, control/models.py
=> Escape more things

control/views.py, static/src/controls/ControlPage.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireDetailPage.vue, static/src/utils/Breadcrumbs.vue, static/src/utils/Sidebar.vue, templates/base.html, templates/ecc/questionnaire_detail.html, templates/ecc/trash.html
Make sidebar collapsible. 
Add breadcrumbs at top of questionnaire pages (otherwise without the sidebar people risk getting lost).
=> Collapse sidebar

static/src/controls/ControlCreate.vue, static/src/controls/NoControls.vue
Add a button for "Ajouter un espace" right inside the first step.
=> Better first experience : add button

control/admin.py
=> Display Responsefiles in Question admin

control/admin.py, static/src/controls/ControlCreate.vue, static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireList.vue, static/src/questions/QuestionFileUpload.vue, static/src/themes/MoveThemesModal.vue, static/src/users/AddUserModal.vue, static/src/users/UpdateUserModal.vue, static/src/users/UserList.vue, static/src/utils/Sidebar.vue, templates/base_email.html
End of my day, I cleaned up little things :)
- Hide SwapEditorButton before data has loaded.
- django admin : Better display for trash status of ResponseFiles
- ARIA accessibility fixes (there are more to do, but it's a start)
- remove little warnings and errors
=> Small frontend fixes

static/src/questions/ResponseFileList.vue, static/src/utils/backend.js
For good security practices, we avoid using v-html because it doesn't escape html. 
The PR removes it in the code, and does some linting/cleanup.
=> Remove use of v-html

user_profiles/tests/test_api.py
Broken by previous PR that removed unused api endpoints.
=> Fix user tests

static/src/questionnaires/QuestionnaireCreate.vue, static/src/questionnaires/QuestionnaireList.vue, static/src/utils/Sidebar.vue
Fixing little final details, and little merge problems.
After that, commando-1 is ready for merge!
=> Commando 1 final bugs

static/src/controls/ControlDeleteFlow.vue, static/src/editors/SwapEditorButton.vue, static/src/users/RemoveUserModal.vue
Remove last occurrences of vue-axios, which were broken since the package is gone now.
=> Bugfix : remove vue axios completely

config/api_views.py, static/src/sidebar.js, static/src/users/AddUserModal.vue, static/src/utils/Sidebar.vue
Don't hardcode e-controle related things.
=> No hardcoding : support email and site url

user_profiles/admin.py
There was no search bar in the userprofiles admin. Added one.
=> Add search bar for userprofiles, by username

faq/admin.py, logs/admin.py, user_profiles/admin.py
Because sometimes it's useful to have them.
=> Add IDs in various admin pages

.env.sample, ecc/settings.py, reporting/tasks.py
Using millis rather than seconds, because hopefully the final value will be in millis... 🤞
=> Make the email spacing time configurable

package-lock.json, package.json, static/src/questionnaires/QuestionnaireCreate.vue, static/src/utils/DateFormat.js
Bug caused by a problem with moment. 
I removed the uses of moment, because it was overkill to import a big package just for that. (one less potentially vulnerable dependency!)
=> Bugfix : dates appear in english

templates/login/email.html, templates/login/email.txt
This should not be merged before corresponding magicauth PR which exposes the necessary context variables : https://github.com/betagouv/django-magicauth/pull/15
=> Update magicauth email message to specify token duration

templates/login/email.html, templates/login/email.txt
We don't have magicauth's version to support this feature, so hardcode it for now.
=> Bugfix for 1.19 : hard code token duration

control/views.py, ecc/urls.py, faq/views.py, templates/base.html, templates/ecc/faq.html, templates/login/login.html
Make the FAQ page accessible without login, and add a link to FAQ in front page.
Edit : a second link
=> FAQ page without login

backoffice/apps.py, backoffice/models.py, backoffice/tests.py, backoffice/views.py, ecc/settings.py, ecc/urls.py, tos/tests/test_middleware.py
Add a backoffice app that replace the standard admin login page
This is a way to remove the next URL redirection
=> Remove next URL for admin

ecc/settings.py
- Default is json
- Browsable API is debug mode
=> Default renderer for Django Rest Framework

static/src/controls/ControlTitle.vue, static/src/users/RemoveUserModal.vue, static/src/utils/ConfirmModalWithWait.vue
For accessibility, the site should be navigable by keyboard.
A small step to help with this : make forms submit when you press ENTER.
=> Confirm forms with ENTER key

tos/templates/tos/tos.html
Add a mention in the TOS that our users are only supposed to use work-issued computers.
=> Update TOS with private computer clause.

print_mime_types.py
Script to print out mime types in a dir, recursively, in csv format, in stdout
=> Script to print out mime types in a dir

static/src/users/AddUserModal.vue, user_profiles/admin.py
added confirmation email when adding a new user
added comfort edits to the admin dash (user join date)
=> Added confirmation email when adding a new user

templates/footer.html
1. Ajout d'un email de confirmation lors de l'ajout d'un utilisateur
2. Ajout d'une colonne date_joined dans l'arrière-cour
3. Allongement de la durée du token de connexion
=> Release notes and version number (1.22)
