betagouv/e-controle

Dockerfile

Postgres is run in a separate container. It's not needed in the django container.

Remove postgres from django container

---

user_profiles/serializers.py
user_profiles/tests/test_api.py

Now we raise validation error when the user alters a control
he does not have access to. We use to filter out the controls,
to only list current logged in user's controls - which was too
restrictive and introduced a bug.

Change the way we protect user altering controls

---

control/api_views.py
control/serializers.py
control/tests/test_api.py

Quand on appelle Questionnaire update, les questions et thèmes qui sont absents du payload sont supprimés de la DB.

Questionnaire api : delete

---

control/api_views.py
control/tests/test_api.py
control/tests/test_pages.py
control/views.py
templates/ecc/questionnaire_detail.html
templates/ecc/questionnaire_list.html

Restrict access to drafts in :
- API access to get draft questionnaire
- page to view draft (questionnaire-detail)
- Accueil page : don't display non-drafts
And some cleaning up of the views : removed unneeded inheritance.

Show draft questionnaires to inspectors only

---

static/src/questions/ResponseDropzone.vue
static/src/questions/ResponseFileList.vue
static/src/utils/utils.js

Bug : 
- reload the questionnaire_detail page (/questionnaire/<id>/)
- trash a response file
- go to another page (e.g. trash page)
- use browser's back button to go back to questionnaire_detail page : the file appears un-trashed.
This is because the questionnaire object is passed in the django template by the server, as part of the html. So when the browser loads the page from cache, it reloads the old version of the questionnaire object alors with the response files.
The same bug happens when adding a response file.
Fix : add a random querystring to the url, so that the page is reloaded forreal on next visit (the browser thinks it's a different page because of the querystring and reloads it)

Bugfix : trashed files reappear

---

templates/ecc/questionnaire_list.html

Put the multicolored colorBar back on the side of Spaces : 
We'll get rid of it once we have better navigation.

Put the multicolored colorBar back

---

static/src/questionnaires/QuestionnaireBodyCreate.vue
static/src/questionnaires/QuestionnaireCreate.vue
static/src/questionnaires/QuestionnaireMetadataCreate.vue

Bug : create a new questionnaire in UI. The default description is not there.
It had disappeared because the first loading of the questionnaire had changed.
Now the default description is set by QuestionnaireCreate, before sending it out to child components.

Questionnaire default description disappeared

---

control/migrations/0001_initial.py
ecc/settings.py
requirements.txt

We want to remove django-filer that's not used anymore.
For that, we have to remove historical references to that app
in migration history. So we hack the migration history  to avoid
importing this app.

Cleanup : retirer django-filer

---

static/src/utils/Sidebar.vue

Fix for 1.9 release. 
Also fixes a bug where the Add Space button appears on the TOS page.

No Add Space button for audited users

---

static/src/controls/ControlCreate.vue

Update error response if there is accent in code référence.
Message d'un contrôleur : 
Bonjour,
Je démarre un contrôle (Juridictionnel lycée Bertran de Born à Périgueux ) avec e-contrôle. 
Ne faudrait-il pas préciser dans la bulle d’information de la case où il faut rentrer un libellé abrégé du contrôle que les accents ne sont pas admis. J’ai eu quelques difficultés avec cela. Il me refusait le nom sans préciser pourquoi.
Sinon, tout va bien. Cela parait très ergonomique et pratique. Je compléterai encore le questionnaire avant de l’envoyer au contrôlé.
Bien cordialement

Allow accented characters in reference_code

---

static/src/questionnaires/QuestionnaireCreate.vue
static/src/questionnaires/QuestionnaireMetadataCreate.vue

- Le texte type dans l'introduction d'un questionnaire a disparu du mode brouillon 
- quand on publie un questionnaire, il y a un pop-up. Il propose un bouton "revenir à l'accueil". Quand on clic on tombe sur une page d'erreur 
- les boutons retour dans la creation de questionnaire etaient aussi cassés, pour la meme raison

1.10 fixes

---

adauth/auth.py
templates/login/login.html

Si un utilisateur (organisme contrôlé), réellement invité, essaie de se connecter mais qu'il voit ce message d'erreur "aucun utilisateur trouvé", il peut y avoir deux explications : email mal orthographié ou l'équipe de contrôle a oublié de l'ajouter à l'espace de dépôt ou mal orthographié.
Au lieu de passer par le support e.contrôle pour faire ces vérifications, autant raccourcir le circuit en les invitants à vérifier ces deux éléments.

Update "aucun utilisateur trouvé"

---

templates/footer.html

Since the released code is the one in the tagged commit, it makes more sense to link to the release notes from the same tagged commit (instead of develop)

Release notes : link to the file from the tagged commit

---

static/css/custom.css

Datepicker is hidden behind footer. 
Solving https://github.com/betagouv/e-controle/issues/384

Display Datepicker in front of footer

---

static/src/editors/SwapEditorButton.vue
static/src/questionnaires/QuestionnaireCreate.vue

New flow : 
- User wants to give up editing rights, and clicks the SwapEditorButton
- The SwapEditorButton, instead of displaying the modal, will send a 'save-draft' event to its parent, QuestionnaireCreate.
- QuestionnaireCreate checks that the questionnaire is saveable by validating the form. 
- It its isn't saveable, abort. If it is, QuestionnaireCreate does the save, then sends event 'show-swap-editor-modal' to SwapEditorButton
- SwapEditorButton shows the modal. 
- < same flow from then on >
In the case that the draft is saveable, but the save fails (network problems, server error...), an error is displayed and the modal opens anyway.

Save draft before swapping editor

---

static/src/editors/RequestEditorButton.vue
static/src/questionnaires/QuestionnaireList.vue

When there is no editor for a questionnaire : 
- In the list of questionnaires, only display one button : Consulter
- when obtaining right, the flow is simplified : no modals, the user is directed to the questionnaire-edit page.
(Tip : lots of whitespace changes in this PR, use no-whitespace feature for reviewing)

Case where there is no editor for a questionnaire

---

static/src/editors/SwapEditorButton.vue
static/src/questionnaires/QuestionnaireCreate.vue

SwapEditorButton doit deja attendre l'event qui vient de QuestionnaireCreate.
Ici, on rajoute un delai à l'envoi de l'event : on attend que le save du questionnaire soit fait. Comme ca le save peut produire le questionnaireId.

Changement Rédacteur - Correctif questionnaire ID vide - alternative

---

static/src/editors/BecomeEditorModal.vue
static/src/editors/RequestEditorButton.vue
static/src/editors/SwapEditorButton.vue
static/src/editors/SwapEditorSuccessModal.vue

Fix for #402 
When you take editor rights, you are redirected to the questionnaire-edit page (instead of home).
When you leave editor rights, you are redirected to the questionnaire-detail page (instead of home).

Return to questionnaire after editor change

---

.eslintrc.json
.vscode/settings.json
package.json
static/css/test/CSSStub.js
static/src/sidebar.js
static/src/utils/Sidebar.vue
static/src/utils/test/Sidebar.spec.js

Premier bug :
Il y a 2 trucs qui sont demandés au serveur en meme temps : le sessionUser (l'utilisateur connecté actuellement) et la liste des controles. Selon celui qui arrive en premier, ca crée le bug.
Si les controles arrivent en premier, alors le menu est contruit. Le menu verifie si l'utilisateur est controleur pour pouvoir lui afficher les brouillons. Or comme l'utilisateur n'est pas encore arrivé du serveur, le test "utilisateur est controleur?" repond "non" (parce qu'il n'existe pas encore, donc il n'est pas controleur!), et du coup le menu lui cache les brouillons.
Fix : 
- maintenant que le store fetch les controles, sidebar recupere les controles du store.
- ajouter watcher sur les loadStatuses, et ne construire le menu que quand les controles et le user sont arrives.
Deuxieme …

Fix bugs in sidebar

---

static/src/editors/RequestEditorButton.vue
static/src/editors/RequestEditorConfirmModal.vue
static/src/editors/RequestEditorModal.vue
static/src/editors/test/RequestEditorButton.spec.js
static/src/utils/EmptyModal.vue

And throw in a few tests.
We disable closing the modal by clicking anywhere except "Confirm" or "Cancel" buttons. This is to avoid a confusion where users clicked outside the modal, and then weren't sure whether the flow happened or not.

Make RequestEditorConfirmModal.vue not closeable

---

static/src/questionnaires/QuestionnaireCreate.vue
static/src/questionnaires/test/QuestionnaireCreate.spec.js

Partial fix for #425 
When editing questionnaire, clicking "Return home" will save questionnaire before leaving.
This means if the questionnaire is in an invalid state, the save will be blocked and the user will be prompted to fix the questionnaire, and stay on the page.
If the questionnaire is valid, but the save fails anyway, the user leaves the page anyway. (we could make them stay... I don't know.)

Save draft questionnaire before returning home

---

static/css/custom.css
static/src/controls/ControlPage.vue
static/src/utils/Sidebar.vue

Fixed by adding artifical vertical margin in the sidebar, to push the footer down at its normal place. Hacky but works.
View with ignore-whitespace, there's some linting.

IE Bugfix : when there are no controls, footer is too high

---

static/src/questionnaires/QuestionnaireBodyCreate.vue

Bugfix : when deleting a question, update the 'order' field, on which is based the 'numbering' field.
Otherwise the docx export has the 'numbering' wrong.

Refresh the order field after deleting a question

---

static/src/questionnaires/QuestionnaireCreate.vue

When move-themes-button is clicked, display spinner and only display modal on the proper page.
Solves a display bug that can happen on slow internet connections.

Spinner for moveThemesModal

---

control/admin.py
control/models.py
logs/admin.py
templates/admin/actstream/action/search_form.html
templates/admin/auth/search_form.html
templates/admin/user_profiles/userprofile/search_form.html
user_profiles/admin.py

- Added ids in display strings (__str__ functions)
- added a column for ID in all pages, generally tried to harmonize various pages to display the same data in the same place
- displayed parents of objects in table views (e.g. for a question, add columns for theme, questionnaire, control) with hyperlinks
- in control page, added users associated to the control
- added instructions for how to search in the action page (how to use the fancy url query params). I added it by overriding a piece of admin template.

Add ids (and other things) in admin pages

---

control/api_views.py
control/tests/test_api.py

- API for upating should not work for deleted control
- API for questions and themes should not work neither

Soft Delete Backend (3): Filter out on API endpoints when control is deleted

---

static/src/questionnaires/QuestionnaireList.vue

For now, revert to the original "Modifier" button without the dropdown menu to delete questionnaires.

Delete Control: Hide "delete questionnaire" button for now

---

templates/user_profiles/email_add_user.html
templates/user_profiles/email_add_user.txt
templates/user_profiles/email_remove_user.html
templates/user_profiles/email_remove_user.txt

Do not use the __str__ function to display models to users, because it contains "id XXX".
The only templates I have found that use this are two email templates, and the Vue code should not be impacted.

Remove ids from user interface

---

static/src/controls/WebdavTip.vue
static/src/questionnaires/PublishFlow.vue
static/src/questionnaires/QuestionnaireMetadata.vue
static/src/questions/ResponseFileList.vue
static/src/utils/Sidebar.vue
templates/ecc/trash.html
tos/templates/tos/tos.html

Add `rel="noopener noreferrer"` on links opening in new tabs, for external links.
I added it for internal links only, it doesn't hurt.

Add rel attribute on links opening in new tabs

---

control/api_views.py
control/tests/test_api.py
static/src/editors/SwapEditorModal.vue
static/src/users/UserSection.vue
static/src/utils/backend.js
user_profiles/api_views.py
user_profiles/tests/test_api.py

On a des problemes avec `/api/users/?control=123`. Le filtrage est compliqué dans le cas où le control existe, mais n'est pas accessible au user.
Je propose de supprimer cette action, et d'utiliser à la place `/api/control/123/users`. 
C'est plus simple parce que ca reutilise les permissions et le queryset du ControlViewSet. Comme ca on fait pas de filtrage compliqué, et les permissions+queryset sont definies une seule fois. Plus c'est simple, moins on a de problèmes!
J'ai aussi supprimé le endpoint pour filtrer les users par profile_type, c'était pas utilisé dans le frontend.

Restrict querying users

---

control/api_views.py
control/permissions.py

- The permission is now split into several classes
- We introduce a permission that checks that only the questionnaire's
editor can change
- We are now usin a object level permission, so there's no need to check
for the `pk` in args

Refactor questonnaire permission

---

static/src/editors/SwapEditorModal.vue

Revert the removal of Vue-axios. It was done only partially, which caused a problem. In next release we are removing vue-axios completely, so this will disappear.
(this is a bugfix on release branch, so I am opting for the smallest change possible, so that we don't have to re-test the interface)

Revert removal of vue-axios

---

package-lock.json
package.json

Unquoted attributes in Django templates are an XSS vulnerability.
Add linter to dev environment that signals when attributes are not quoted.
To install : 
- npm install (the package htmlhint was added)
- install linter in VSCode (if you use VSCode) : https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint

Add HTMLHint as html linter, to avoid unquoted attributes in Django templates

---

static/css/custom.css
static/src/utils/Sidebar.vue
templates/base.html

Fixes 2 problems : 
- when page scrolls horizontally, the sidebar button moves away from the sidebar
-> fixed by removing the sideways scroll, which was an IE bug anyway.
- sidebar toggle button was displayed under sidebar
-> fixed by increasing z-index.

Bugfix : sidebar for ie

---

static/src/questionnaires/QuestionnaireCreate.vue
static/src/utils/StickyBottomMixin.js

Broken in 1.16 (known issue).
It was broken because the bottom-bar on IE is made sticky by our own custom function, and that function broke because the bottom-bar was not displayed at the start (it was hidden while content was loading).
So I changed the v-if (which removes elements completely from the DOM) to a v-show (which only hides them), and added a hack to adjust the height of the element (when it's hidden, the height is 0, and that messed up the rest).
I also added a second hack for the width, because it was not stretching all the way because of negative margins... Or maybe because of flex... Who knows...

Bottom bar broken in IE

---

static/src/control-detail.js
static/src/controls/ControlDetail.vue
static/src/controls/ControlPage.vue
static/src/questionnaire-create.js
static/src/questionnaire-detail.js
static/src/questionnaires/QuestionnaireDetail.vue
static/src/utils/Sidebar.vue
templates/base.html
templates/ecc/control_detail.html
templates/ecc/questionnaire_create.html
templates/ecc/questionnaire_detail.html

Until now the sidebar was a completely separate bundle of js, with its own build target.
For the pages which are fully built in Vue (control-detail, questionnaire-detail, questionnaire-create), this PR uses the Sidebar.vue component inside the main js bundle, and gets rid of the separate sidebar bundle.
Note that the separate sidebar bundle is still built, for the pages like FAQ which have a Vue sidebar but no Vue in the rest of the page.
There are also changes to make the components use the Vuex store instead of passing data through props.

Move sidebar inside page bundles

---

static/src/controls/ControlCreate.vue
static/src/utils/Sidebar.vue

Fix for bug in IE introduced in 1.16, where the modal for adding a new control appeared greyed out.
(not sure yet in which branch we will merge this, so don't merge for now)
Edit : merge into develop, it will go in 1.18

Bug on "Add Control" modal in IE

---

reporting/tasks.py

Our emails are being blocked because we are over quota. As a temporary fix, wait 1min after each email for the celery task of the daily report emails. 
Also removed some information from the logs for privacy (control name, recipient email)
I don't know python well, so if using time.sleep is a problem, please advise.

Add a 1min wait to space out emails

---

package-lock.json
package.json
templates/base_tabler.html

Upgrade jquery to 3.5.1, to fix a compatibility problem with boostrap, that appeared in jquery 3.5.0
The questionboxes did not open any more when they were clicked (multiple browsers)

Update jquery to fix questionbox dropdown

---

static/src/controls/WebdavTip.vue
static/src/store.js

Wait for the config to be fetched (so that the video url is filled in) before we display the videoplayer.

Bugfix for 1.18 : video player broken

---

static/src/users/AddUserModal.vue
tests/data/test.sh
user_profiles/serializers.py
user_profiles/tests/test_api.py

Was causing a bug, where if you tried to add a user that already exists but with different casing for the email, the server crashed.
Fixed the frontend so that it lowercases emails and doesn't cause the bug, and also the backend to avoid seeing the bug in API.

Bugfix : lowercase email when adding user

---

.env.sample
ecc/settings.py

Not tested on DEV. We want to be sure not to break the prod machines...

Add setting to use console email backend for development

---

templates/user_profiles/email_add_user.html
templates/user_profiles/email_add_user.txt

Remove dot after url in email and move it to new line, for easy copy-pasting. We had someone who was copy-pasting with the dot, and could not log in.

Remove dot after url in email

---

ecc/settings.py
templates/base.html
templates/login/wait.html

The default magicauth wait page uses an external stylesheet (from https://tabler.github.io) which is blocked by our CSP. So style is broken.
This PR overrides the default template provided by magicauth, to use our own, with the stylesheet served from our own server.

Fix style for wait page

---

templates/base.html
templates/login/wait.html
tos/templates/tos/tos.html
tos/views.py

The TOS (terms of service, at `/cgu`) is accessible without login (this is on purpose, it is linked from the home page). 
But without login, some features break : the sidebar, the FAQ link, the user button at top right.
This PR hides the broken features when the user is not logged in : sidebar, and topbar elements.

TOS page without login

---

static/src/questionnaires/QuestionnaireCreate.vue

Save message was not visible enough for users to notice when the save had failed. This caused some loss of data in the past. (issue : https://github.com/betagouv/e-controle/issues/222 and https://github.com/betagouv/e-controle/issues/237)
This PR displays a "saving..." message for 2 seconds at least (so that users have time to see the message) and then a success or error message. This is copied from what google docs does.
Saving : 
Done with success : 
Done with error : 
Errors are not fully displayed in the save message, because they are already displayed in the error bar at the top of the page (but that's debateable, we could display them)

Make save message visible

---

static/src/users/AddUserModal.vue

Problème : les contrôleurs créent des comptes avec des emails erronés et ne s'en rendent pas compte. Ensuite les nouveaux utilisateurs n'arrivent pas à se connecter. (issue : https://github.com/betagouv/e-controle/issues/373)
Solution : 
Un écran de confirmation qui suggère d'envoyer le mail tout de suite :
Quand on clique le bouton ca crée un mail déjà écrit, avec le destinataire déjà rempli. Comme ca si l'email renseigné est erroné, le mail va revenir à l'envoyeur (la personne qui crée le compte), et il va se rendre compte que quelque chose ne va pas.

Suggest an email for new users

---

.env.sample
config/api_views.py
ecc/settings.py
static/src/users/AddUserModal.vue

Add a verification step when adding a new inspector user : if the email doesn't end with one of the expected endings, show a warning. 
There should be no changes for audited users.
Edit : also includes cleaning up the navigation buttons (suivant, retour, annuler)

Less email input errors : warning for inspector email ending

---

static/src/questionnaires/PublishFlow.vue
static/src/questionnaires/QuestionnaireCreate.vue

Adds a step to the questionnaire modal with pre-filled email for controlled organisms.

Add questionnaire modal to send confirmation email
